#!/bin/sh -e

# AEL Installer for Arch Linux

logo() {
    printf "
==========================================
        __              __   __   _
       /  )        /   /  ) /   _//
      /--/ __  _. /_  /--/ /--  /  
     /  (_/ (_(__/ /_/  (_(___,/___

==========================================
        Arch Linux AEL Installer
==========================================\n"
}

verify_efi() {
    if [ -f /sys/firmware/efi/fw_platform_size ]; then
        EFI_BITS=$(cat /sys/firmware/efi/fw_platform_size)

        if [ "$EFI_BITS" -eq 64 ]; then
            BOOT="UEFI 64"
        elif [ "$EFI_BITS" -eq 32 ]; then
            BOOT="UEFI 32"
        else
            printf "ERROR: Unknown EFI platform size detected.\n" >&2
            exit 1
        fi

    else
        BOOT="BIOS"
    fi
}

verify_root() {
    if [ $(id -u) -ne 0 ]; then
        printf "ERROR: This script must be run as root.\n" >&2
        exit 1
    fi
}

verify_fzf() {
    if ! command -v fzf >/dev/null 2>&1; then
        pacman -Sy --noconfirm fzf >/dev/null 2>&1 || {
            printf "ERROR: Could not install fzf. Check your ethernet connection.\n" >&2
            exit 1
        }
    fi
}

verify_pacman() {
    if [ -f /var/lib/pacman/db.lck ]; then
        if pgrep -x pacman >/dev/null 2>&1; then
            printf "ERROR: Pacman is currently running. Close it before proceeding.\n" >&2
            exit 1
        else
            rm -f /var/lib/pacman/db.lck
        fi
    fi
}

verify_iso() {
    if [ ! -f /run/archiso/bootmnt/arch/x86_64/airootfs.sfs ]; then
        printf "ERROR: This script must be run from an Arch Linux installation ISO.\n" >&2
        exit 1
    fi
}

verify() {
    verify_iso
    verify_efi
    verify_root
    verify_pacman
    verify_fzf
}

font() {
    setfont ter-v18b
}

selection() {
    printf "%b\n" "$options" | fzf --prompt "$prompt"
}

disk() {
    options=$(lsblk -dn -o NAME,SIZE,TYPE,TRAN | awk '$3 == "disk" && $4 != "usb" && $1 !~ /^(loop|ram|sr|fd)/ {printf "/dev/%s (%s)\n", $1, $2}')
    prompt="Select a disk: "

    selected=$(selection)
    DISK=$(printf '%s' "$selected" | cut -d' ' -f1)
}

region() {
    options=$(curl -fs http://bin.christitus.com/raw/dalopenori)
    prompt="Select your country: "
    COUNTRY=$(selection)

    case "$COUNTRY" in
        "Brazil")
            LOCALE="pt_BR.UTF-8"
            ;;
        "United States")
            LOCALE="en_US.UTF-8"
            ;;
        *)
            options=$(awk '{ sub(/^#/, ""); if ($1 ~ /\.UTF-8$/) print $1 }' /etc/locale.gen)
            prompt="Select your language: "
            LOCALE=$(selection)
            ;;
    esac

    LOCALE_LONG="${LOCALE} UTF-8"

    options=$(awk '/^[^#]/ { print $3 }' /usr/share/zoneinfo/zone.tab)
    prompt="Select your timezone: "
    TIMEZONE=$(selection)

    options=$(localectl list-keymaps)
    prompt="Select your layout: "
    KEYMAP=$(selection)

    printf "\nFetching fastest mirrors for %s...\n" "$COUNTRY"
    reflector --country "$COUNTRY" --age 12 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
}

user() {
    while :; do 
        printf "\nEnter your username: " 

        read -r username_input
        username_input=$(printf '%s' "$username_input" | xargs)
        username_raw=$(printf '%s' "$username_input" | tr '[:upper:]' '[:lower:]')

        if [ "$username_raw" != "root" ] && printf '%s' "$username_raw" | grep -Eq '^[a-z_][a-z0-9_-]{0,31}$'; then
            USERNAME="$username_input"
            break
        else
            printf "Invalid username. Try again.\n"
        fi
    done

    while :; do
        printf "\nEnter your password: "
        stty -echo
        read -r password_input1
        stty echo

        printf "\nRe-enter your password: "
        stty -echo
        read -r password_input2
        stty echo

        if [ "$password_input1" != "$password_input2" ]; then
            printf "\nPasswords don't match. Try again.\n"
        elif [ "$password_input1" = "$password_input2" ] && [ -n "$password_input1" ]; then
            PASSWORD="$password_input1"
            break
        else
            printf "\nInvalid password. Try again.\n"
        fi
    done

    while :; do
        printf "\n\nName your machine: "

        read -r hostname_input
        hostname_input=$(printf '%s' "$hostname_input" | xargs)
        hostname_raw=$(printf '%s' "$hostname_input" | tr '[:upper:]' '[:lower:]')

        if printf '%s' "$hostname_raw" | grep -Eq '^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$'; then
            HOSTNAME="$hostname_input"
            break
        else
            printf "Invalid hostname. Try again."
        fi
    done
}

verify
font
logo
user
disk
region
clear

printf "
==========================================
            Formatting Disk
==========================================\n"

sgdisk -Z "$DISK"
sgdisk -a 2048 -o "$DISK"

sgdisk -n 1::+1G --typecode=1:ef00 --change-name=1:'EFI System' "$DISK"
sgdisk -n 2::-0 --typecode=2:8300 --change-name=2:'Linux Root' "$DISK"

partprobe "$DISK"

printf "
==========================================
           Creating Filesystem
==========================================\n"

if [ "$DISK" =~ "nvme" ]; then
    part1=${DISK}p1
    part2=${DISK}p2
else
    part1=${DISK}1
    part2=${DISK}2
fi

mkfs.fat -F 32 "$part1"
mkfs.ext4 "$part2"

mount "$part2" /mnt
mount --mkdir "$part1" /mnt/boot

printf "
==========================================
          Installing Base System
==========================================\n"

pacstrap -K /mnt base base-devel linux-lts linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt <<EOF

printf "
==========================================
              Network Setup
==========================================\n"

pacman -S --noconfirm --needed networkmanager 
systemctl enable NetworkManager

nc=$(grep -c ^cpu\ cores /proc/cpuinfo)
printf "
==========================================
   Optimizing MAKEFLAGS and COMPRESSION
     settings for your %s-core system
==========================================\n" "$nc"

TOTAL_MEM=$(awk '/MemTotal/ {print $2}' /proc/meminfo)

if [ "$TOTAL_MEM" -gt 8000000 ]; then
    sed -i "s/#MAKEFLAGS=\"-j2\"/MAKEFLAGS=\"-j$nc\"/" /etc/makepkg.conf
    sed -i "s/COMPRESSXZ=(xz -c -z -)/COMPRESSXZ=(xz -c -T $nc -z -)/" /etc/makepkg.conf
fi

printf "
==========================================
            Region Settings
==========================================\n"

sed -i "s/^#${LOCALE_LONG}/${LOCALE_LONG}/" /etc/locale.gen
locale-gen
printf "LANG=%s\n" "${LOCALE}" > /etc/locale.conf

timedatectl set-timezone "${TIMEZONE}"
timedatectl set-ntp true

mkdir -p /etc/X11/xorg.conf.d
printf "KEYMAP=%s\n" "${KEYMAP}" > /etc/vconsole.conf
printf "Section \"InputClass\"\n\tIdentifier \"system-keyboard\"\n\tMatchIsKeyboard \"on\"\n\tOption \"XkbLayout\" \"%s\"\nEndSection\n" "${KEYMAP}" > /etc/X11/xorg.conf.d/00-keyboard.conf

EOF